{
  "services": {
    "tailscale": {
      "image": "tailscale/tailscale@sha256:c507f3a2a6ab1cabd8d809b98edeb41edbd5c3fb6ad9632ffd098b4c7d0b4065",
      "platform": "linux/amd64"
    },
    "portainer": {
      "image": "portainer/portainer-ce@sha256:03f94a406496dc84d37b552795fc424ccad8d0d7200353b6a82915f6e8f73ab0",
      "platform": "linux/amd64"
    },
    "dnscrypt-proxy": {
      "image": "klutchell/dnscrypt-proxy@sha256:a98e8d13314fa8b75620026441b1d6581e2b55189509a794500c5c86064df810",
      "platform": "linux/amd64"
    },
    "headscale": {
      "image": "headscale/headscale@sha256:8833f828b414c0907b7e5c71da76473216fe17cce0818a166b536ec552c0903f",
      "platform": "linux/amd64"
    },
    "headplane": {
      "image": "ghcr.io/tale/headplane@sha256:394483fd2336ce6b15df360c3e118ddfd45eb8140fe21df9f2611077f5d79d22",
      "platform": "linux/amd64"
    },
    "npm": {
      "image": "jc21/nginx-proxy-manager@sha256:4393e642e233e5efd5adeb7f10918d4aaea71c9ed875b94190273fc8e87f9594",
      "platform": "linux/amd64"
    },
    "cloudflare-ddns": {
      "image": "favonia/cloudflare-ddns@sha256:5e61736b982b87d84a1120b4767c4deff0f2cc55ca3ee9dcb1dc58623039b5cb",
      "platform": "linux/amd64"
    },
    "aiometadata": {
      "image": "ghcr.io/cedya77/aiometadata@sha256:9bff687d7f213e401475951cb0be882eeec45d919e0659a2a7dc58d9b329c67e",
      "platform": "linux/amd64"
    },
    "mediaflow-proxy-light": {
      "image": "ghcr.io/mhdzumair/mediaflow-proxy-light@sha256:44e10959417a2de569a998af28bd59ac14ab34225795de8326f60699717fbb5b",
      "platform": "linux/amd64"
    },
    "aiostreams": {
      "image": "ghcr.io/viren070/aiostreams@sha256:bcb643691a40e1024ff101ad356935fad1a77a878fb5def5e6663cedf05dc741",
      "platform": "linux/amd64"
    },
    "pgbouncer": {
      "image": "edoburu/pgbouncer@sha256:9c78945868a6a142c7fc40ccd843bbe5a606df163c7ffce4de70e0d628d696a2",
      "platform": "linux/amd64"
    },
    "postgres": {
      "image": "postgres@sha256:650d7a867dc5336eff67802a1417fcc801821d73d824c608e80afbde792fe6e1",
      "volumes": [
        "postgres-cluster:/var/lib/postgresql"
      ],
      "platform": "linux/amd64"
    },
    "redis": {
      "image": "redis@sha256:2c2dff791878316e3b083188be0d578423b24813cdda5de0e80ea4f7b3e6bfd6",
      "platform": "linux/amd64"
    },
    "watchtower": {
      "image": "nickfedor/watchtower@sha256:45b54f6dc15227cfb38dbb826f2881aa0f56aaf0c255cdbb38bd80e598bdca9a",
      "platform": "linux/amd64"
    },
    "honey": {
      "image": "ghcr.io/dani3l0/honey@sha256:fe6ce43acf93a211ab63cf247e4ce573cb63a41608092f0bffb1b3bf72527ac5",
      "platform": "linux/amd64"
    },
    "teamspeak": {
      "image": "teamspeaksystems/teamspeak6-server@sha256:d845f803aecf842c2df034c959c23ff2462357bacafb3807500885c5ec170fa1",
      "platform": "linux/amd64"
    },
    "microwarp": {
      "image": "ghcr.io/ccbkkb/microwarp@sha256:d5b709efd49dbec3a965c617eb263b46cdf1449e65776d1b9a351927439b2b17",
      "platform": "linux/amd64"
    },
    "gost": {
      "image": "gogost/gost@sha256:55f05a58541f69bd7aa5fb9ee24fda12669430fb71489496473ecf15c32bcc8e",
      "platform": "linux/amd64"
    },
    "oauth2-proxy": {
      "image": "quay.io/oauth2-proxy/oauth2-proxy@sha256:8498b0d0ef0a7b29686414000a08aee467f02d0299c9ed1e006a8f33fc017916",
      "platform": "linux/amd64"
    },
    "easyproxy": {
      "image": "ghcr.io/realbestia1/easyproxy@sha256:9b64eaccee664ea7b05a39afbee3321aaa56a5be4e78bd2fb7457f5bd8a3e646",
      "platform": "linux/amd64"
    },
    "streamvix": {
      "image": "qwertyuiop8899/streamvix@sha256:8ac6ace2fe07004f997f6d6451c5f77ef3870f6f5bcc3abd9420e9fc40542134",
      "platform": "linux/amd64"
    },
    "tvvoo": {
      "image": "qwertyuiop8899/tvvoo@sha256:f8798651ab092bb915e08692c579fdab240cf0ba606c9f49663b74162c292697",
      "platform": "linux/amd64"
    },
    "aiomanager": {
      "image": "ghcr.io/sonicx161/aiomanager@sha256:d054c8b5795e93ce828098eddd7e0f1a07da2d6e31c91c8d1c3412256ec3c7ac",
      "platform": "linux/amd64"
    },
    "deunhealth": {
      "image": "qmcgaw/deunhealth@sha256:db1e4fcd3aceeb0da34a83f7a8a5432df586e6d0388ddb6ad8dd7b479e4aa25d",
      "platform": "linux/amd64"
    },
    "gluetun": {
      "image": "qmcgaw/gluetun@sha256:12df8b20528d4cd5e9b6e827d40f2886cf78e53e7e9afc750050648c31183793",
      "platform": "linux/amd64"
    },
    "comet": {
      "image": "g0ldyy/comet@sha256:dca62133336e02784d02aaad861381820674d1c8e3e98a03797610b81ee4defe",
      "platform": "linux/amd64"
    },
    "cometnet": {
      "image": "g0ldyy/comet@sha256:dca62133336e02784d02aaad861381820674d1c8e3e98a03797610b81ee4defe",
      "platform": "linux/amd64"
    },
    "stremthru": {
      "image": "muniftanjim/stremthru@sha256:3db9d5f373759fdbab97366ad6a106288eb753e9a07c9ec0f0e096acc8553321",
      "volumes": [
        "stremthru-data:/app/data"
      ],
      "platform": "linux/amd64"
    },
    "jackett": {
      "image": "lscr.io/linuxserver/jackett@sha256:7b19f4f6ac33d855ca9226600ecbd096ee678f66da28b13a7c09980b035ff583",
      "platform": "linux/amd64"
    },
    "seanime": {
      "image": "umagistr/seanime@sha256:d74dcac9d5c29f74d980cccf5311a2212fe202b85308032d8665a15469824363",
      "platform": "linux/amd64"
    },
    "seanime-shared": {
      "image": "umagistr/seanime@sha256:d74dcac9d5c29f74d980cccf5311a2212fe202b85308032d8665a15469824363",
      "platform": "linux/amd64"
    }
  },
  "volumes": {
    "portainer-data": {
      "external": false
    },
    "pgdata": {
      "external": false
    },
    "redis-data": {
      "external": false
    },
    "teamspeak-data": {
      "external": false
    },
    "warp-data": {
      "external": false
    },
    "postgres-cluster": {
      "external": false
    },
    "stremthru-data": {
      "external": false
    }
  }
}
